# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shorturl',
            options={'verbose_name': 'Mini URL', 'verbose_name_plural': 'Minis URL'},
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='pseudo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
